explicit yarn before build to fix missing karma-phantomjs-launcher
$ ng test
13 07 2017 09:29:09.417:ERROR [config]: Error in config file!
 { Error: Cannot find module 'karma-phantomjs-launcher'
    at Function.Module._resolveFilename (module.js:469:15)